spring:

#  redis:
#    host: 192.168.118.133
#    port: 6379
#    password: 15172415712
#    client-name: jedis
#    jedis:
#      pool:
#        max-active: 10
#        min-idle: 5
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true #使用IP注册进来
  application:
    name: BackAdmin  #为当前应用取名

  datasource:
    url: jdbc:mysql://localhost:3306/druid?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 262007

    druid:
      filters: stat,wall #底层开启的功能，stat(sql监控)，wall(防火墙)
      filter:  #对filters里面的stat和wall进行详细配置
        stat:
          slow-sql-millis: 1000  #慢查询时间，单位毫秒
          log-slow-sql: true  #日志是否记录慢查询
          enabled: true  #开启Durid的监控统计功能
        wall:
          enabled: true  #是否开启防火墙
      stat-view-servlet:  #配置监控页功能
        enabled: true  #开启监控页
        login-username: admin  #监控页账号名
        login-password: admin  #监控页密码
        reset-enable: false  #禁用监控页的重置按钮
      web-stat-filter:  #采集web-jdbc关联监控的数据（开启druid监控中的Web应用和URI监控界面）
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,./druid/*'
      aop-patterns: com.example.demo.*  #监控SpringBean
    tomcat:
      max-active: 12

#配置Mybatis的规则
mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml  #指定mybatis的全局配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml #指定sql映射文件
  #可以不写全局配置文件,所有的全局配置文件都放在configuration配置项中即可,并且config-location和configuration不能同时存在
  configuration: #指定mybatis的全局配置文件中的相关配置项，相当于直接在configuration中配置mybatis全局配置文件中的配置了
    map-underscore-to-camel-case: true #开启驼峰命名法

#management是所有actuator的配置
#management.endpoint.端点名.xxxx: 对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: true #默认开启所有监控端点
    web:
      exposure:
        include: '*' #以web方式暴露所有端点
  endpoint:
    health:
      show-details: always